### ISSUE TITLE
ABC script

### ISSUE THREAD

**Issue by fpga-1234** [EliasVansteenkiste/EvaluationFramework#1]
would you mind to publish the ABC script that produced the best results, as promised in your publication?

**Comment by fpga-1234** [comment]
a

**Comment by fpga-1234** [comment]
sorry to bother you again, but i cant find any ABC script except 'best_logic_optimization.script' which is 0 byte. Would you please provide your ABC script that you mention in the publication?

**Comment by EliasVansteenkiste** [comment]
@fpga-1234 ,
I committed our best script. Take into account that this script is fine tuned for Vivado 2015.
