### ISSUE TITLE
abc.rc

### ISSUE THREAD

**Issue by fpga-1234** [EliasVansteenkiste/EvaluationFramework#2]
one final issue with your optimization script:
as it does not seem to be a built in command and I cant find it in the default 'abc.rc',
did you define 'synch2' somewhere in your abc.rc and can you please provide it?

**Comment by EliasVansteenkiste** [comment]
Please ask Alan Mishchenko to provide you the definition of synch2.
It was available to me when I was at Xilinx, but now not anymore.

**Comment by fpga-1234** [comment]
My bad, the command is  '&synch2' and built into new ABC versions. Thanks for your effort!
